import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/index.js";
import Footer from "@/components/footer";
import Sidebar from "@/components/sidebar/sidebar";
import DrawerContextComponent from "@/context/drawerContext";

const montserrat = Montserrat({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const fetchGameCategories = async () => {
  try {
    const data = await fetch("http://localhost:3000/api/categories/all");
    const categories = await data.json();
    return categories;
  } catch (error) {
    console.log(error.message, "categories error");
  }
};

export default async function RootLayout({ children }) {

  const gameCategories = await fetchGameCategories();

  return (
    <html lang="en">
      <body className={montserrat.className}>
        <DrawerContextComponent>
          <div style={{ width: "100%" }}>
            <Navbar gameCategories={gameCategories}/>
            <div style={{  }}>
              <main className="flex gap-3 justify-center">
                <div className="sidebarcontainer">
                  <Sidebar gameCategories={gameCategories} />
                </div>

                {children}
              </main>
            </div>
            <Footer />
          </div>
        </DrawerContextComponent>
      </body>
    </html>
  );
}
