import { Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/index.js";
import Footer from "@/components/footer";



const montserrat = Montserrat({
  weight: ['400','700'],
  subsets: ["latin"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div style={{ width: "100%",
        //  background: "#F8F8F8" 
         }}>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
